spring:
  datasource:
    url: jdbc:mysql://192.168.27.217:3306/academy_2022?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: root # MySQL korisnicko ime
    password: root # MySQL lozinka
    #driver-class-name: com.mysql.jdbc.Driver #MySQL Driver -> MySQL 5.X.X
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver -> MySQL 8.X.X

server:
  port: 8443

# custom twitter configuration
twitter-api:
  url: https://prod.twitter.com/api/v1/get-tweets
  username: account-prod-username
  password: account-prod-password
  authentication-token: 123asdlakjlk1j23lk1j2l3k