spring:
  application:
    name: Logate Academy Demo Application
  profiles:
    active: dev

  cache:
    jcache:
      config: classpath:ehache.xml

  liquibase:
    change-log: classpath:liquibase/master.xml

db-url: test123

jwt:
  secret: bXktc2VjcmV0LWtleQo=
  validityInMinutes: 5