spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy_2022?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: root # MySQL korisnicko ime
    password: 1234 # MySQL lozinka
    #driver-class-name: com.mysql.jdbc.Driver # MySQL Driver -> MySQL 5.X.X
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver -> MySQL 8.X.X
  jpa:
    show-sql: true

  liquibase:
    contexts: dev


server:
  port: 8080

fake-store-api:
  base-url: https://fakestoreapi.com
  product-part: /api/products
  category-part: /api/categories
  cart-part: /api/cart

auth-key: LogateAcademy2022

fs:
  base-path: C:\Users\Korisnik\Desktop\logate_academy\